// <auto-generated />
using ConventionsAide.VenueOrders.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConventionsAide.VenueOrders.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(VenueOrdersDbContext))]
    [Migration("20220711060320_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConventionsAide.VenueOrders.Domain.VenueOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.Property<long>("VenuesConfirmationFlowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VenuesConfirmationFlowId");

                    b.ToTable("VenueOrders", (string)null);
                });

            modelBuilder.Entity("ConventionsAide.VenueOrders.Domain.VenuesConfirmationFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConventionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VenuesConfirmationFlows", (string)null);
                });

            modelBuilder.Entity("ConventionsAide.VenueOrders.Domain.VenueOrder", b =>
                {
                    b.HasOne("ConventionsAide.VenueOrders.Domain.VenuesConfirmationFlow", "VenuesConfirmationFlow")
                        .WithMany("VenueOrders")
                        .HasForeignKey("VenuesConfirmationFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenuesConfirmationFlow");
                });

            modelBuilder.Entity("ConventionsAide.VenueOrders.Domain.VenuesConfirmationFlow", b =>
                {
                    b.Navigation("VenueOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
